### ISSUE TITLE
Captcha after third login try

### ISSUE THREAD

**Issue by interduo** [iredmail/iRedAdmin#16]
https://packagist.org/packages/dsoares/rcguard

Could You add captcha after third login try (to roundcube client and admin panel) in default install?

**Comment by iredmail** [comment]
Since iRedAdmin(-Pro) logs succeeded/failed logins to syslog, how about ban the client with Fail2ban?

**Comment by interduo** [comment]
Fail2ban is not good because many ISP share IP's for many users. You could block access for other users.

**Comment by iredmail** [comment]
How about TOTP as 2-factor authentication instead of captcha?

**Comment by interduo** [comment]
This should be an option next to captcha. It's little different case. 
Captcha plugin is very easy to install and no need to teach users and no need to install any app on Your phone.

**Comment by iredmail** [comment]
What i thought is, captcha doesn't actually prevent hacking by guessing login username+password although it slows down the process, but 2FA does.

Since `rcguard` is not official plugin, we prefer not to enable it by default, because it may have compatibility issue after upgraded Roundcube package, but iRedMail team can not help fix it as soon as possible.

**Comment by iredmail** [comment]
btw, `rcguard` "requires reCAPTCHA API keys to work properly", iRedMail installer can not get the api key for each installation, so it's impossible for iRedMail installer to enable it for sysadmin.

**Comment by interduo** [comment]
ok - I see Your point now. Installer could ask for API key.

**Comment by iredmail** [comment]
> ok - I see Your point now. Installer could ask for API key - If You put key enable rcguard.

No.

- This is not official plugins, so we don't enable it by default.
- It's confusing to ask for such key during installation wizard, it adds extra burden to sysadmin because they don't know what it is, or it requires additional steps to obtain a key.

> This plugin is in https://plugins.roundcube.net/#/packages/dsoares/rcguard - so it is not so official but approved.

I disagree. It's just a place to let third-party plugin developers to upload and share their plugins, it doesn't mean Roundcube team "approve" (or audit, or certificate) any of them.

Let's stop here please.
